### ISSUE TITLE
Session recordings from Fringe 2015?

### ISSUE THREAD

**Issue by ebekker** [dotnetfringe/2015.dotnetfringe.io#1]
Were the session from .NET Fringe 2015 recorded and are they available to the public somewhere?

I couldn't find any information about it on the [old site](2015.dotnetfringe.org) and the [schedule on Laynard](http://lanyrd.com/2015/dotnetfringe/schedule) didn't include any links to videos.

But I heard on Channel 9's discussion of this year's 2016 Fringe that there are plans to record and release all the sessions.

**Comment by Adron** [comment]
This year all sessions will indeed be recorded. I'll see if I can find 2015's videos. @thoward do you know where they are?

**Comment by glennblock** [comment]
Yes the 2015 sessions were recorded.

https://www.youtube.com/channel/UCIz73jo7KPqVTssbUmiIfXg
